CREATE TABLE IF NOT EXISTS accounts
(
    seq_no     INT AUTO_INCREMENT PRIMARY KEY,
    id         VARCHAR(36) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    bestScore  INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user
(
    seq_no     INT AUTO_INCREMENT PRIMARY KEY,
    id         VARCHAR(36) UNIQUE NOT NULL,
    device_id  VARCHAR(255) UNIQUE NOT NULL,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_coordinates
(
    user_seq_no INT PRIMARY KEY,
    x_coord     DECIMAL(10, 6) NOT NULL,
    y_coord     DECIMAL(10, 6) NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_seq_no) REFERENCES user(seq_no) ON DELETE CASCADE
);